"""empty message

Revision ID: 51a2c98b5ee3
Revises: e1f4ed21c444
Create Date: 2020-10-23 00:07:53.730561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51a2c98b5ee3'
down_revision = 'e1f4ed21c444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('social_id', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'users', ['social_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'social_id')
    # ### end Alembic commands ###
